# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0004_auto_20171116_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='visiters',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
