# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_owner'),
        ('blog', '0006_auto_20171101_1611'),
    ]

    operations = [
    ]
