# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 09:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practice',
            name='rangef',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='practice',
            name='ranget',
            field=models.PositiveIntegerField(),
        ),
    ]
