# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20171103_1015'),
        ('photo', '0002_auto_20171012_1835'),
        ('photo', '0002_auto_20171101_1106'),
    ]

    operations = [
    ]
