# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-11-08 02:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('photo', '0002_auto_20171102_1908'),
        ('photo', '0002_auto_20171103_1015'),
        ('photo', '0002_auto_20171101_1106'),
    ]

    operations = [
    ]
